### ISSUE TITLE
PublicPath helper breaks view

### ISSUE THREAD

**Issue by matthewjamesr** [leafsphp/leafMVC#15]
Self-explanatory. PublicPath for js and css has worked on top-level views, but not nested on all nested views.

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ getenv('APP_NAME') ?? 'Leaf MVC' }} | @yield('title')</title>
    <link rel="shortcut icon" href="https://leafphp.netlify.app/img/logo.png" type="image/x-icon">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ PublicPath('./assets/css/styles.css') }}">
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700;display=swap">
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="{{ PublicPath('./assets/js/jquery-3.6.0.min.js') }}" type="text/javascript"></script>
    <script src="{{ PublicPath('./assets/js/main.js') }}" type="text/javascript"></script>
</head>

<body>
    <div class="container welcome">
        <div class="row">
            <div class="col s12 m4">
                <h1><a href="/">Glint</a></h1>
                <h5><small class="text-muted">Bite-sized intel delivered</small></h5>
            </div>
            <div class="col m8 d-sm-none d-md-block">
                <ul class="float-end nav">
                    <li><a href="/countries/china">China <img src="{{ PublicPath('flags/china_flag.png') }}"></img></a></li>
                    <li><a href="/countries/dprk">DPRK <img src="{{ PublicPath('flags/dprk_flag.png') }}"></img></a></li>
                    <li><a href="/countries">All</a></li>
                </ul>
            </div>
        </div>
    </div>
	@yield('content')
</body>

</html>
```
Here is the sub-view that is not pulling in the public path resources:
```
@extends('index')

@section('title', $country['country'])

@section('content')
<div class="container countries">
        <div class="row justify-content-md-center gy-4">
            <div class="col s12 hero">
                <h1 class="text-center">We have intel on the biggest threats</h1>
                <p>It's the <b>baddies</b>. Daily updates on the biggest threats to global security.</p>
                <div class="request">
                    <a class="btn btn-dark" href="/countries">Get briefed</a>
                </div>
            </div>
        </div>
    </div>
@endsection
```

Any help much appreciated!

**Comment by matthewjamesr** [comment]
For some reason, public path on this page wants to load everything from that resource's folder.

![image](https://user-images.githubusercontent.com/303321/148008764-2bcf98e4-464c-472e-b2f4-fccd6b40c9a5.png)

**Comment by mychidarko** [comment]
Hi @matthewjamesr, I'll check out this issue. Thanks

**Comment by matthewjamesr** [comment]
@mychidarko Sounds good. If you have the bandwidth, a quick-fix would be amazing. I am testing out leafphp by building a small news site and cannot proceed till this is rectified.

So far I like it, though! Nice work.

**Comment by mychidarko** [comment]
Hi @matthewjamesr, can I get a little info on your setup? I cloned your project glint and the `PublicPath` seems fine. I'm using the leaf CLI `serve` command, and the PHP in-built server loads it fine as well.

![image](https://user-images.githubusercontent.com/26604242/148128801-b2926bff-0ced-41a0-89e1-5ebef927d03f.png)

**Comment by mychidarko** [comment]
Also, just to try, pls remove the `./` from the path in `PublicPath`. So you will have something like `PublicPath('assets/js/main.js')` instead

**Comment by mychidarko** [comment]
I've found the source of the issue, I'll resolve it soon. Thanks for the patience 😊

**Comment by mychidarko** [comment]
Fixed now. Steps to fix in your project:

- Remove unused doctrine/dbal package (ignore all warnings at the end)

```sh
composer remove doctrine/dbal
```

ignore all warnings at the end

- Update leaf MVC core

```sh
composer require leafs/mvc-core ^1.1.6 -W
```

**Comment by matthewjamesr** [comment]
@mychidarko Now that I have followed those steps, it seems that my env is being ignored, and leaf is trying to use laravel forge?

```
Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO) in C:\Users\me\OneDrive\Documents\dev\PHP\glint\vendor\illuminate\database\Connectors\Connector.php:70 Stack trace: #0 C:\Users\me\OneDrive\Documents\dev\PHP\glint\vendor\illuminate\database\Connectors\Connector.php(70): PDO->__construct('mysql:host=127....', 'forge', '', Array) #1 C:\Users\me\OneDrive\Documents\dev\PHP\glint\vendor\illuminate\database\Connectors\Connector.php(46): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=127....', 'forge', '', Array) #2 C:\Users\me\OneDrive\Documents\dev\PHP\glint\vendor\illuminate\database\Connectors\MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=127....', Array, Array) #3 C:\Users\me\OneDrive\Documents\dev\PHP\glint\vendor\illuminate\database\Connectors\ConnectionFactory.php(184): Illuminate\Database\Connectors\MySqlConnector->connect(Array) #4 [internal function]: Illuminate\Database\ in C:\Users\me\OneDrive\Documents\dev\PHP\glint\vendor\illuminate\database\Connection.php on line 705
```

**Comment by matthewjamesr** [comment]
I fixed the env var issues. Your newest code has as such:

`_env("DB_XYZ", "xxxx")`

Removing the underscore fixed.

`env("DB_XYZ", "xxxx")`

**Comment by mychidarko** [comment]
Thanks. Leaf MVC will be updated as such 🚀
