### ISSUE TITLE
Leaf Auth Not Working

### ISSUE THREAD

**Issue by matthewjamesr** [leafsphp/leafMVC#17]
@mychidarko Hello again. This time, I cannot get `\Leaf\Auth` helpers to work.

I have generated login logic via `php leaf scaffold:auth` and that worked.

Below is the error output:

```
Fatal error: Uncaught Error: Call to undefined method Leaf\Auth::guard() in C:\Users\me\OneDrive\Documents\dev\PHP\glint\app\controllers\Auth\LoginController.php:12 Stack trace: #0 [internal function]: App\Controllers\Auth\LoginController->show() #1 C:\Users\me\OneDrive\Documents\dev\PHP\glint\vendor\leafs\router\src\Router\Core.php(451): call_user_func_array(Array, Array) #2 C:\Users\me\OneDrive\Documents\dev\PHP\glint\vendor\leafs\router\src\Router\Core.php(417): Leaf\Router\Core::invoke('\\App\\Controller...', Array) #3 C:\Users\me\OneDrive\Documents\dev\PHP\glint\vendor\leafs\router\src\Router\Core.php(349): Leaf\Router\Core::handle(Array, true) #4 C:\Users\me\OneDrive\Documents\dev\PHP\glint\public\index.php(130): Leaf\Router\Core::run() #5 C:\Users\me\OneDrive\Documents\dev\PHP\glint\index.php(24): require_once('C:\\Users\\me\\One...') #6 {main} thrown in C:\Users\me\OneDrive\Documents\dev\PHP\glint\app\controllers\Auth\LoginController.php on line 12
```

**Comment by matthewjamesr** [comment]
Also, I have ran `leaf install auth`, with no fix.

**Comment by matthewjamesr** [comment]
I have also tried `\Leaf\Auth\Session` and changing the config to use it.

When that is implemented, I get an `htmlspecialchars` error that is generated from `Anchor`.

**Comment by mychidarko** [comment]
Hi @matthewjamesr, sorry I wasn't able to reply immediately. I'll check this out and have it corrected
